name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: cargo clippy
        run: cargo clippy

      - name: cargo fmt
        run: cargo fmt --check

      - name: cargo test
        run: cargo test
